name:                github-access
version:             0.1.0.0
github:              "sum-n/github-access"
license:             BSD3
author:              "Suman Neupane"
maintainer:          neupanes@tcd.ie
copyright:           "2020 Suman Neupane"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sum-n/github-access#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- servant
- servant-client
- http-client

library:
  source-dirs: src

executables:
  github-access-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-access

tests:
  github-access-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-access
